### ISSUE TITLE
Wrapped WebSocket does not implement the WebSocket interface

### ISSUE THREAD

**Issue by HollieSteinman-AccessIQ** [newrelic/newrelic-browser-agent#1173]
## Description

The WebSocket wrapper added in #1159 does not fully implement the WebSocket interface, as defined in the [WebSocket standard](https://websockets.spec.whatwg.org/#the-websocket-interface). Interface constants such as `CONNECTING`, `OPEN`, `CLOSING` & `CLOSED` are seemingly not defined on the wrapped `WebSocket`.

This becomes an issue when implementations expect the `WebSocket` to have these constants set. For example, anyone using the [`reconnecting-websocket`](https://github.com/pladaria/reconnecting-websocket/blob/05a2f7cb0e31f15dff5ff35ad53d07b1bec5e197/reconnecting-websocket.ts#L17-L20) package will face this issue when the wrapped `WebSocket` is used.

We haven't had a deeper dive into the WebSocket wrapper implementation, so there is a possibility there are further compatibility issues due to not fully implementing the WebSocet interface.

## Steps to Reproduce

Instrument a browser application using v1.265.0 of the agent.

The WebSocket wrapper then does not define the `CONNECTING`, `OPEN`, `CLOSING` & `CLOSED` constants.

## Expected Behavior

The WebSocket wrapper should implement the WebSocket interface as specified in WebSocket standard: https://websockets.spec.whatwg.org/#the-websocket-interface

## Relevant Logs / Console output

The `WebSocket` class as defined in version <1.265.0, or without any instrumentation:

<img width="581" alt="image" src="https://github.com/user-attachments/assets/97c01682-fb85-4fee-ab6e-b11cf2897eba">

The `WebSocket` class in v1.265.0:

![image](https://github.com/user-attachments/assets/ff065658-6daa-4acb-b912-bedee30be6a3)

## Your Environment

* All browsers
* Browser agent version v1.265.0

**Comment by dotorify** [comment]
Oh!.. I'm experiencing the same issue.

Due to the changes in v1.265.0, there is an issue where WebSocket connections are not possible when using third-party libraries like reconnecting-websocket (https://github.com/pladaria/reconnecting-websocket/blob/master/reconnecting-websocket.ts#L20) to build services. This has caused actual problems in product services.

Overriding the browser's built-in WebSocket can lead to unexpected errors in the runtime environment.

If overriding is necessary, I believe the correct approach is to follow the native definition by default and guide the optional use of the overridden library. Additionally, all properties and methods provided by the native WebSocket should be supported to prevent issues.

**Comment by andredriem** [comment]
Also this happened after a simple reboot in my rails server in PRODUCTION. There is some serious issue with that gem if it is self-updating outside the asset pipeline.

**Comment by cwli24** [comment]
Apologies for the all the trouble caused here, folks. We rolled prod back to the previous 1.264.0, so @andredriem if you reboot again, your ruby APM should pull that in. (It's actually not just Ruby but all our APM agents pull in any new agent release on restart or after some days afaik.)

**Comment by ramchandra-st** [comment]
Hi Folks,

I also face issues due to this. Now it is resolved, that's great.

I use `reconnecting-websockets`, I see we can pass `ws` instance to this lib via the `option` argument, so is it a good idea to pass it to this lib explicitly instead of letting it use the global ws instance to avoid a similar incident in future?

**Comment by cwli24** [comment]
We're re-deploying with patch 1.265.1 which takes out the websocket wrappings in the problematic 1.265.0. This should take effect for APM instrumented users on the next app restart or after a few days by the apm language agents.

Please keep an eye out and ping me here if it's still causing the same integration issue even with that patch. (It really shouldn't.)

**Comment by garhiggins** [comment]
If you read this issue, you would think the bug is as simple as: _We didn't fully implement WebSocket, and that caused a bug for some users_ - that's true, but that's a fairly minor bug.

The real issue is this:  _NewRelic did a release of code outside of a versioned release. Any app using NewRelic was updated with the new code, outside of any standard release process, and could not rollback - the only remedy for users was to do an emergency release with all references to newrelic's sdk removed._

Your release process is broken. We've removed newrelic from our app to avoid any further breakage.

**Comment by cwli24** [comment]
There's also [the version pinning method via NerdGraph API/GQL](https://docs.newrelic.com/docs/apis/nerdgraph/examples/browser-monitoring-config-nerdgraph/#browser-agent-version-pinning) that some have done for 1.265, albeit not avail from the UI, but the point about release process is valid.

I've brought up the risk and impact of having browser agent release automatically rolled out during server uptime disregarding user deployment and testing processes before and will do so again, though that effect was an organizational decision made before my time.

**Comment by cbikar** [comment]
@ellisong @metal-messiah @cwli24 The issue seems to be happening again and causes issues with other scripts on a website that leverage websockets. Was any new update pushed out that overwrites the native websocket function?

**Comment by cwli24** [comment]
@cbikar Yes. What's the exact issue you're seeing? The static constants should be there now, so unless it's the same problem as the original post here, can you open a new issue?

**Comment by cbikar** [comment]
@cwli24 we opened https://github.com/newrelic/newrelic-browser-agent/issues/1387
