### ISSUE TITLE
NewRelic overwrites window.Promise

### ISSUE THREAD

**Issue by graemechapman** [newrelic/newrelic-browser-agent#187]
## Description
As per the title, replacing browser built-ins is generally a bad idea, and can interfere with other code which relies on this functionality. 

## Steps to Reproduce
Visit a website running NewRelic, and try to use window.Promise.

## Expected Behavior
<img width="219" alt="image" src="https://user-images.githubusercontent.com/17706618/154475048-c872ea91-9d8d-4206-a8c8-a9ec7ad9e162.png">

## Relevant Logs / Console output
<img width="501" alt="image" src="https://user-images.githubusercontent.com/17706618/154474974-121cb8ad-e2f8-4e54-b0a8-9d82c6d6dc02.png">

## Your Environment
Browser name and version: Chrome 98
Operating System and version: macOS Big Sur

## Additional context
n/a

**Comment by aubreymasten** [comment]
Hey @graemechapman, is there a specific issue that you're running into where our Promise instrumentation is interfering with other code?

**Comment by graemechapman** [comment]
> Hey @graemechapman, is there a specific issue that you're running into where our Promise instrumentation is interfering with other code?

Hi @aubreymasten I have a class extending from Promise, when run in conjunction with newrelic the additional methods on these class instances are not accessible.

I have been able to work around this for now by grabbing the original promise constructor from `window.NREUM.o.PR` but obviously this is not ideal.

**Comment by kucaahbe** [comment]
have the same issue as well, when NewRelic kicks in TinyMCE editor can not start:
<img width="461" alt="Знімок екрана 2022-06-29 о 2 12 51 пп" src="https://user-images.githubusercontent.com/93769/176423661-6483ca3d-a6b4-423e-b183-bc5525b2adb4.png">

<img width="1011" alt="Знімок екрана 2022-06-29 о 2 14 22 пп" src="https://user-images.githubusercontent.com/93769/176423692-a1383b27-db7c-4841-98a2-4218263a9c0b.png">

**Comment by graemechapman** [comment]
> have the same issue as well, when NewRelic kicks in TinyMCE editor can not start: <img alt="Знімок екрана 2022-06-29 о 2 12 51 пп" width="461" src="https://user-images.githubusercontent.com/93769/176423661-6483ca3d-a6b4-423e-b183-bc5525b2adb4.png">
> 
> <img alt="Знімок екрана 2022-06-29 о 2 14 22 пп" width="1011" src="https://user-images.githubusercontent.com/93769/176423692-a1383b27-db7c-4841-98a2-4218263a9c0b.png">

This is an even bigger problem than the one I reported this for, and is likely to have a much more widespread impact.

**Comment by cwli24** [comment]
@kucaahbe I'm unable to reproduce this issue on a vanilla page's agent for the current (unreleased) version **and** a production customer's website v1216 agent. I haven't looked into TinyMCE specifically, but a potential cause for conflict as had happened before is other libraries or API implementations that also touches the global `Promise` object, such as Zone.js for Angular. Would like to table and revisit this after next version release if it's still an issue. Thanks!

**Comment by cwli24** [comment]
> > Hey @graemechapman, is there a specific issue that you're running into where our Promise instrumentation is interfering with other code?
> 
> Hi @aubreymasten I have a class _extending from Promise, when run in conjunction with newrelic the additional methods on these class instances are not accessible._
> 
> I have been able to work around this for now by grabbing the original promise constructor from `window.NREUM.o.PR` but obviously this is not ideal.

Hi @graemechapman, could you clarify a little more about what and where the friction is please? I did not find any issue with calling the instance method of an inherited-from-Promise class--am I misunderstanding? 

Specifically, the (spa flavor) agent will wrap around the `window.Promise` object and alter it; that **is** the functionality of the object. What problem are you attempting to solve? Do you just want access to the untampered `Promise`? Or is there some property or method that you cannot find on the altered `Promise` which should exist?

**Comment by kucaahbe** [comment]
> @kucaahbe I'm unable to reproduce this issue on a vanilla page's agent for the current (unreleased) version **and** a production customer's website v1216 agent. I haven't looked into TinyMCE specifically, but a potential cause for conflict as had happened before is other libraries or API implementations that also touches the global `Promise` object, such as Zone.js for Angular. Would like to table and revisit this after next version release if it's still an issue. Thanks!

hello @cwli24 , thanks for the reply. In our case TinyMCE wasn't the cause of the issue: its code uses the `Promise.allSettled` and that's how we spotted the issue.
On the other hand, I've checked the vanilla page as well and no issues there, so I've checked our site again and found the re-producible case; the issue looks like is some conflict between the NewRelic agent code and ES6 shim library (https://github.com/paulmillr/es6-shim). 
This is the test case (please note, didn't place NewRelic agent code snippet there):
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>NewRelic issue #187 test case</title>

    <script>
      if (Promise.allSettled) {
        alert('Promise.allSettled initially exists')
      } else {
        alert('Promise.allSettled does not exist')
      }
    </script>

    <script type="text/javascript">
      NewRelic agent code snippet here
    </script>

    <script src="https://cdn.jsdelivr.net/gh/paulmillr/es6-shim@0.35.6/es6-shim.js"></script>
  </head>

  <body>
    <script>
      console.log('Promise.allSettled:', Promise.allSettled)
      if (Promise.allSettled) {
        alert('Promise.allSettled exists')
      } else {
        alert('Promise.allSettled is overrided')
      }
    </script>
  </body>
</html>

```

**Comment by samdenty** [comment]
This is breaking our application 

<img width="915" alt="CleanShot 2023-02-17 at 17 11 22@2x" src="https://user-images.githubusercontent.com/13242392/219719004-a120587f-44f1-44bb-bf21-1aedccc18bb4.png">

**Comment by patrickhousley** [comment]
@samdenty Can you look to see what version of the agent is being loaded? Maybe provide a link to your website? I just checked another site that is loading the latest version of our agent (1225) and `o instanceof Promise` reports true.

**Comment by samdenty** [comment]
`new Promise(() => {}) instanceof Promise` works
but
`(async () => {})() instanceof Promise` doesnt

**Comment by cwli24** [comment]
> `new Promise(() => {}) instanceof Promise` works but `(async () => {})() instanceof Promise` doesnt
> 
> the URL is https://stackblitz.com/~/github.com/withastro/docs

Thanks for bringing this up & to our attention. v1225 included a re-working of our Promise wrapping because what we were doing before was directly modifying the native Promise that async/await implements. -- Apologies for causing breakage!

Going forward, our (wrapped) Promise will likely remain that way; we may re-discuss the implementation, though I feel this is the right thing to do. It's very similar to [Bluebird's dilemma in that async/await's returned Promise cannot be replaced](https://github.com/petkaantonov/bluebird/issues/1434) with our custom Promise.

I'm not sure you're going to get the (revert) solution from this agent, to be frank. However, there are ways on your end to "fix" it:
- casting async's native Promise to our Promise using `Promise.resolve(asyncFunc())`
- check it against `newrelic.o.PR` instead (this is the original Promise object), if `instanceof` is needed(?)
- (obligatory:) using Promise instead of async/await
- (last resort:) swap the original Promise back and use it over ours by `window.Promise = newrelic.o.PR` after agent code -- this will make SPA nonfunctional

**Comment by samdenty** [comment]
we're running a fork of microsoft vscode codebase directly in the browser. We try to keep modifications to a minimum, so only the last resort option (swapping the original promise back) would work.

I'm not personally a fan of overriding globals, but maybe we do that hack to keep using new relic? @fvsch

I would much prefer this as an option (disabled by default maybe?)

**Comment by patrickhousley** [comment]
@samdenty Do you have a staging environment/site that we can use to debug?

**Comment by cwli24** [comment]
To clarify, it's not particularly `instanceof Promise`, but specifically within the context of checking `async`'s return against it that's problematic. 
I imagine historically we've swapped out globals for dev convenience so they did not have to change _anything_ vs. replacing all the `Promise` with something like `newrelic.Promise` per adoption; this could be subject to change, but I'm afraid at this point it would only offend the vast majority of existing users.

Regardless, the native global is still there (hidden) and left untouched, which to me is better than modifying its prototype, irrespective of the global ref replacement. And unfortunately, that means `async` is native (since we have no way to wrap the keyword) and its returned promise is native. That's the impasse, and I'm more pressed about
`(async()=>{})().then(...)`
not using our `then` than about the `instanceof` comparison honestly.

**Comment by samdenty** [comment]
I presumed you were already doing this and this was an edge case that didn't work - but are you able to define a Symbol.hasInstance on your custom promise, that returns true when both a native promise and mocked promise is passed

**Comment by patrickhousley** [comment]
@samdenty I am going to open a new issue for this so we can better track it.
