### ISSUE TITLE
Loading chunk 692 failed on Firefox 109.0 and Safari 16.2

### ISSUE THREAD

**Issue by ilario-pierbattista** [newrelic/newrelic-browser-agent#392]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Starting from 2023-01-30 we started to get the following load error from users with Firefox 109.0 and Safari 16.2 browsers (both desktop and mobile versions).

> Loading chunk 692 failed. (error: https://js-agent.newrelic.com/692.215647de-1223.js)

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

I didn't manage to reproduce the error. I've tried to use Firefox 109 (on Ubuntu), but it seems to work.
On the other hand, I see a lot of incoming traffic from Firefox 109 browsers that doesn't report a load failure.
It seems to fail randomically.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

The script load should never fail.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

```
Loading chunk 692 failed.
(error: https://js-agent.newrelic.com/692.215647de-1223.js)
```

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* php NR agent version: 10.5.0.317
* the agent is configured to auto inject the js script

**Comment by patrickhousley** [comment]
Morning @ilario-pierbattista and thanks for reporting this issue. With version 1220, the browser agent began using lazy chunked loading making the initial code that has to be injected into the HTML smaller. We have noticed that certain browsers with more restrictive privacy settings like Firefox with Strict privacy control enabled, DuckDuckGo browser, and ad blockers will block the agent from loading the additional JS resources it needs at runtime. This results in the error you are describing.

We are planning to make that message in the browser console more user friendly. We are also looking for feedback on other options for addressing this concern. Please feel free to share your opinions and feedback, we take all feedback very seriously and ensure it feeds into product development at New Relic.

**Comment by ilario-pierbattista** [comment]
Hello @patrickhousley, thank you for your reply. 
I confirm that configuring Firefox in strict privacy mode made me reproduce the load error.

Maybe the lazy chunked loading could be disabled by configuring the agent?

**Comment by patrickhousley** [comment]
Thanks for the feedback @ilario-pierbattista , that is one of the options we are considering. Below is the size difference in the code that must be injected into the HTML.

## With Code Splitting

File Size | File Name
-- | --
53K | nr-loader-full-1223.min.js
32K | nr-loader-rum-1223.min.js
59K | nr-loader-spa-1223.min.js

## Without Code Splitting

File Size | File Name
-- | --
104K | nr-loader-full-1223.min.js
85K | nr-loader-rum-1223.min.js
110K | nr-loader-spa-1223.min.js

**Comment by bartosz-zolynski** [comment]
Confirmed for the browser versions mentioned. Also seen on Safari 16.0. As a "bonus", all e2e tests written in Cypress also started to fail across all the different sub-projects. Interestingly enough, we had `*.newrelic.com` included on the `blockHosts` list in Cypress config but it didn't prevent tests to fail. Only after removing this domain from `blockHosts` made tests working again. Not sure what could be the cause of it?

**Comment by patrickhousley** [comment]
How are you injecting the agent? The agent is usually contained in the HTML file as an inline script. It will then lazy load chunks from our CDN `https://js-agent.newrelic.com/`. With that `blockHosts` in place, the agent will not load and will `console.error` an error like the one in the original post.

With 1223, we resolved an issue where some sites were redefining the global `self` variable that was breaking the `webpack` lazy loader. However, we have also noticed that the chunks can be blocked due to browser privacy settings and/or ad blockers.

If we revert back to a single agent script without the use of lazy chunks, privacy settings and ad blockers may still affect the capturing of data. Privacy settings and ad blockers may also block the network requests the agent makes to send the collected data to New Relic.

As an interim solution, we are making a change in 1224 (eta tbd) to capture the chunk load errors and provide a better message to the console. For the long term, we are actively exploring options with regards to the above mentioned privacy settings and ad blocker issue.

**Comment by cwli24** [comment]
We found where we had internal uncaught Promises that was causing this problem; culprit was introduced in v1223 restructuring. Thank you for the report!

**Comment by smokinjoe** [comment]
> https://issues.newrelic.com/browse/NEWRELIC-6637

Your cert has expired - I'm trying to determine if this issue is similar to one I'm experiencing when trying to integrate 1.257.0 into my react app but chrome refuses to let me view the page
