### ISSUE TITLE
Doesn't work on older browsers (eg Safari on older iPads)

### ISSUE THREAD

**Issue by neilgd** [newrelic/newrelic-browser-agent#474]
I have an SSR next js app.

A lot of my customers run, eg, Safari on iOS 12 and 13. I have the following line in my nextjs app:

```
 const browserTimingHeader = newrelic.getBrowserTimingHeader({
      hasToRemoveScriptWrapper: true,
      allowTransactionlessInjection: true,
    });
```

The agent that's injected contains unsupported javascript (eg the `?`. nullish coalescing operator)

Since this crashes their browsers, I can't use it for *any* of my customers (my pages are cached, so there's no way of conditionally injecting the code). Which means I can't use the browser timing features at all.

Is there any way of changing tsconfig.json to target eg ES6 instead?

Thanks!

**Comment by patrickhousley** [comment]
Hi @neilgd. Thanks for reporting this issue. The browser agent is built using Babel with a target of the last 10 versions of Chrome, Firefox, Edge, and Safari. That means that our build produces code that targets language syntax and features that may not be supported in older browsers. You can check our browser support documentation [here](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/#browser-types). The `tsconfig.json` file is only used for the generation of our typings files.

You do have a few options if you need to support older browsers.
1. You can open a feature request with New Relic to add support for older browsers. This might look like a flag that you can configure in NR1 to enable use of a polyfilled ES5 agent bundle instead of what is shipped by default.
2. If you don't care to switch from APM injection to Copy/Paste, you can fork this repository and modify the build to match the browsers your application needs to target. This gives you a lot of control over the build of the agent and where the agent is loaded from but you will also need to take care of keeping your fork up to date.
3. We also have a pre-release NPM package available that you can implement within the web part of your application. Keep in mind that this is a pre-release and the package can change. However, you can import the NPM package and configure your project build to apply transformations to the package exported code.

**Comment by neilgd** [comment]
@patrickhousley Thank you very much for the reply! I will go with option 2 (there seems to be no way for me to do 1, and 3 seems more complicated!).

Thanks again!
