### ISSUE TITLE
Provide minified bundle like in `0.0.9` version

### ISSUE THREAD

**Issue by luisbravoa** [newrelic/newrelic-browser-agent#481]
Are you thinking on providing a bundled version of the library? The last version `0.0.9` did provide a bundled version that we could just inject into the `index.html` of the app and initialize early in the app's lifecycle, instead of including it in the application bundle.

## Summary

Having the bundled version allows the browser agent to be initialised before the application so fatal errors can be reported.

## Desired Behavior

Provide an browser agent bundle like in version `0.0.9`.

**Comment by patrickhousley** [comment]
Thanks for reaching out @luisbravoa. We will take this question internally and discuss amongst the team.

**Comment by patrickhousley** [comment]
Hi @luisbravoa I thought I would reach out and let you know we have discussed internally whether we want to include the bundles in the npm package and have concluded, at least for now, that we will not be including them. If you would like to use a `<script src=""` element to pull in the browser agent, our recommendation is to use our public CDN.

While we desire that customers using the Copy/Paste method of installing the browser agent copy the snippet from New Relic and embed the loader in their HTML, we understand that one size does not fit all. If you would like to use a script src tag, below is an example.

```
<script src="https://js-agent.newrelic.com/nr-loader-spa-1.239.1.min.js"></script>
```

All the loaders follow the same naming pattern `nr-loader-[agentType]-[version].min.js` where `[agentType]` can be `rum` for the lite agent, `full` for the pro agent, and `spa` for the spa agent. The `[version]` value will always match the version in our [published releases](https://github.com/newrelic/newrelic-browser-agent/releases). You may also leave off the `.min` part if you would like an unminified version of the agent loader.

Keep in mind that this is not an officially supported installation mechanism because it does require the browser to download an additional resource before the agent can wrap globals and start intercepting events for harvesting. However, we do our best to try and capture as much information as possible to provide a complete observability picture. We do not currently recommend using `async` or `defer` for the agent loader script. Either of these could exacerbate the issue of missing data and, if the agent is not started before page load, may result in the agent not collecting any data. These attributes could also change the order in which globals are wrapped leading to strange interactions with other third-party libraries.

**Comment by luisbravoa** [comment]
Hello @patrickhousley ,

Thanks for the consideration. My concerned would be the additional requests needed for the agent to be initialized. For our use case we prefer having the agent embedded in the document so we can minimize points of failure at application startup. 
To this end we are currently bundling the agent implementation ourselves and injecting it in the document, which work we expected.

Thanks again.

**Comment by patrickhousley** [comment]
Hi @luisbravoa and thanks for providing more information about your use-case. Is your application served through some type of SSR or server-side application that can utilize APM injection? A lot of our language/APM agents support injecting the browser agent into the HTML.

We also have [NerdGraph](https://docs.newrelic.com/docs/apis/nerdgraph/examples/browser-monitoring-config-nerdgraph/) and [Rest](https://docs.newrelic.com/docs/apis/rest-api-v2/browser-examples-v2/add-or-list-browser-apps-api-v2/) APIs that you could use to retrieve all the details you need from New Relic for instrumenting a specific browser entity. This is actually what the APM agents are doing behind the scenes to inject the browser agent 😉 .

You could also use something like node-fetch to retrieve the JS loader snippet from our CDN during your build.
