### ISSUE TITLE
routing is not working

### ISSUE THREAD

**Issue by nisarg2023** [newrelic/newrelic-browser-agent#679]
![1](https://github.com/newrelic/newrelic-browser-agent/assets/125979189/5ad2c63c-318d-4044-b9ed-f2a4cac18fe2)

routing does not work when I add a new relic browser script but without the new relic script it works properly
I copied and past script from the new relick dashboard and removed <script> stage

I connect my next js 13 app with Browser successfully but problems in routine a routine is not work properly
And I also try to connect my react js app with Browser it work properly

**Comment by patrickhousley** [comment]
Hi @nisarg2023 have you by chance look at https://github.com/vercel/next.js/discussions/53746

**Comment by nisarg2023** [comment]
@patrickhousley  Yes with next js 13.4.20-canary.5. Work properly

**Comment by patrickhousley** [comment]
@nisarg2023 The SPA feature is not compatible with that version of NextJS. You could disable that feature by creating a custom `Agent` instance instead of `BrowserAgent`. If you need help with that, let me know and please provide the code you are using to instantiate the NR browser agent. Otherwise, you will need to upgrade the version of NextJS you are using.

**Comment by patrickhousley** [comment]
Closing. This is a known issue in the NextJS router version 13.3.2-canary.2 and fixed in version 13.4.20-canary.5. Please reference the [docs](https://docs.newrelic.com/docs/browser/single-page-app-monitoring/troubleshooting/nextjs-app-router-links-broken/) for more information.
