### ISSUE TITLE
Investigate: Add CORP headers

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#74]
Chrome 92 will force certain interactions to have a Cross-Origin-Resource-Policy: cross-origin header present.  Currently our CDN and Ingest do not return this header.  We need to investigate the impact this will have and whether we need to take action.  Chrome 92 is set for July.

FR for Demplatform team

**Comment by martinkuba** [comment]
## Explainer

Customer can setup their web pages to be cross-origin isolated. This is done by returning the two response headers with the HTML document:

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

After this, when the page requests a resource (e.g. external script), the browser will allow it in the page only if the resource includes this response header:

```
Cross-Origin-Resource-Policy: cross-origin
```

If the header is not present, or it has value of “same-origin” or “same-site”, the browser will not allow it on the page, and the following error will appear in the browser console:

```
net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
```

## Impact

The impact on the Browser Agent is the following

* it only impacts customers that explicitly enable cross-origin isolation on their HTML documents
* with cross-origin isolation enabled, the second agent script (from js-agent.newrelic.com) will not load, and as a result the agent will not run at all

## Resolution

In order to allow the agent to run in pages with cross-origin isolation, the following needs to happen:

* the JS resources from js-agent.newrelic.com must include the “Cross-Origin-Resource-Policy” header with value “cross-origin”
* the JSONP call from bam.nr-data.net (first agent harvest call) must also include the same response header

**Comment by rr0214** [comment]
This is in process by another New Relic team and estimated to be released in the next 1-2 weeks.
