### ISSUE TITLE
Route console log to new relic logs

### ISSUE THREAD

**Issue by murphpdx** [newrelic/newrelic-browser-agent#761]
I'd like a setting in the new relic brower agent that will automatically hook into the console.log/console.error functions and send the logs to new relic logging. I would also like it to not log in the browser. Alternatively, an api call that will send logs to new relic. It does not have to hook into console but it would be nice if it did. 

## Summary

Forward logs to new relic via the browser agent.

## Desired Behavior

Conditionally override the console.log, console.error, console.debug, console.info etc functions so that they send logs to new relic and do not log in the console. 

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by patrickhousley** [comment]
Hi @murphpdx and thanks for the feature request. This is actually on our roadmap for the quarter starting in January. We did do some work in a past version of the agent to gauge the data that would be sent if we automatically instrumented the `console` global. Unfortunately we found that extremely large objects are sometimes logged to the console in production systems resulting in a performance issue when we have to serialize it for sending to New Relic.

If you, or any community member or customer, has any suggestions around what you would like to see with this feature, please let us know either here, in our [forums](https://forum.newrelic.com/s/), or by reaching out to customer engagement or support.

Some things that we are trying to consider:
- Do we need to implement log levels, what are they, and what do they map to on the console?
- What limits can/should we put in place on what gets serialized for logging?
  - Object depth limit?
  - Only flat objects?
- Do we need an API to allow customer code to inspect a log before it is serialized?
  - Log filtering
  - Custom serialization
- How/Should we handle obfuscation of log data?

**Comment by sconzof** [comment]
Hi! Piggy-backing on the request from @murphpdx 
This feature set would be very useful for some of our internal applications.

**Comment by CavalcanteLeo** [comment]
any news about this?

**Comment by patrickhousley** [comment]
@CavalcanteLeo this work is on our roadmap to start this quarter.

**Comment by FranciscoKloganB** [comment]
Just shimming in, this feature might be nice as an opt-in.

Some projects allow the use of `console.log` freely in the code and remove them for production builds using `vite`/`webpack`/`rollup` directives.

**Comment by CavalcanteLeo** [comment]
in reality, instead of sending the console.log automatically, I would prefer something to manually send it to  new relic, something like `newrelic.log(text: string), and on the frontend I can abstract it, and create a function with the logger I want to use...
```ts
  const log = (text: string): void => {
    newRelic.log(text)
    if (runtimeConfig.public.ENV === 'dev') {
      console.log(text) // here I could use anything I want... like pino or winston
    }
  }
 ```

in this case, we don't rely on the console.logs only

**Comment by caviyacht** [comment]
Optionally allowing each method in a config would be preferred. Our main focus is to get console.error captured as it would help track down a ton of problems.

The console.log could become a ton of noise and high data ingest, but toggling it on and off at will would be super beneficial.

**Comment by piyushchauhan2011** [comment]
Thank you for good work on logs

**Comment by patrickhousley** [comment]
Hi everyone. With version 1.261.0, we released two new API methods that you can use to send logs to New Relic for your browser apps.

- [log](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/log/): This works just like `noticeError` where you can send logs to NR manually within your code.
- [wrapLogger](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/wraplogger/): This works by wrapping methods of some provided object. When that method is called, the agent will capture the arguments and send a log to NR. Be careful here because we serialize the first argument to a string and assume that is the log message. If you send a large object as that first parameter, you could severely degrade the performance of your app.

We do not currently support automatically capturing logs or automatically wrapping `console`. You will have to determine what fits best in your app and call the appropriate API methods. If you have any questions, please let us know. You can also reach out on support.newrelic.com.
