### ISSUE TITLE
Expose web-vitals library globally

### ISSUE THREAD

**Issue by EduardDopler** [newrelic/newrelic-browser-agent#822]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Since v1.229.0 newrelic-browser-agent includes Google's [`web-vitals`](https://www.npmjs.com/package/web-vitals) library. Often it's useful for site owners to add custom logic/events to CWV events, so if NewRelic exposed the already available library, site owners wouldn't need to download, execute and register it again.

## Desired Behavior

Expose your included web-vitals in the global window object if it's not already present. The official global name the library uses is "webVitals".

## Possible Solution

```js
window.webVitals = windows.webVitals || YOUR_LIBRARY_REFERENCE
```

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by patrickhousley** [comment]
Thank you for reaching out @EduardDopler. I have converted the internal ticket into a feature request and we will take it under advisement. Since this is a feature request, you may want to reach out to New Relic support or use our [community forums](https://support.newrelic.com/s/) so that the feature request is properly attributed to your internal account.

**Comment by EduardDopler** [comment]
Support case created. Thank you @patrickhousley

**Comment by patrickhousley** [comment]
For now we are taking the approach of not exposing any of the third party libraries that the agent depend upon. I understand @EduardDopler the desire and use case you have here. I think you may be able to use our NPM package to have better control over the third party libraries and reduce the amount of duplication.
